/**
 * brushStroke.js
 *
 * Convert a free-hand brush stroke (a polyline of pointer-sampled points)
 * into a closed polygon outline. The brush is an ellipse that may be rotated
 * and squashed to give a calligraphic feel: when the user moves the pointer
 * along the brush's major axis the stroke is thin, when they move across it
 * the stroke is thick. Roundness 1.0 = perfectly round brush (uniform width),
 * roundness 0.2 = highly elliptical (pronounced calligraphy).
 *
 * The polygon is generated by projecting each centerline point ±half-width
 * along the local normal, where half-width is the ellipse's extent in that
 * normal direction. Result is a left-side polyline + reversed right-side
 * polyline, which closes into a single contour.
 */

/**
 * @param {Array<{x:number, y:number}>} points  centerline samples, len ≥ 2
 * @param {number} thickness                    major-axis diameter in font-units
 * @param {number} roundness                    0.2–1.0 (1.0 = circle)
 * @param {number} [angleDeg=35]                rotation of the brush major axis
 * @returns {Array<{x:number, y:number}>}       closed polygon (no duplicate)
 */
export function strokeToPolygon(points, thickness, roundness, angleDeg = 35) {
  if (!points || points.length < 2) return []
  const a = thickness / 2                            // major radius
  const b = (thickness / 2) * Math.max(0.05, Math.min(1, roundness))
  const ang = (angleDeg * Math.PI) / 180
  const ux  = Math.cos(ang),  uy  = Math.sin(ang)    // major-axis direction
  const vx  = -Math.sin(ang), vy  = Math.cos(ang)    // perpendicular

  const left  = []
  const right = []
  const n = points.length
  for (let i = 0; i < n; i++) {
    const p = points[i]
    let tx, ty
    if (i === 0)            { tx = points[1].x   - p.x;        ty = points[1].y   - p.y }
    else if (i === n - 1)   { tx = p.x - points[i - 1].x;      ty = p.y - points[i - 1].y }
    else                    { tx = points[i + 1].x - points[i - 1].x
                              ty = points[i + 1].y - points[i - 1].y }
    const tlen = Math.hypot(tx, ty) || 1
    tx /= tlen; ty /= tlen
    const nx = -ty, ny = tx                          // left normal

    // Half-width along the normal: ellipse extent in direction (nx, ny).
    // (a · cos)² + (b · sin)² where the angle is between (nx,ny) and the major axis.
    const cosA = nx * ux + ny * uy
    const sinA = nx * vx + ny * vy
    const half = Math.sqrt((a * cosA) ** 2 + (b * sinA) ** 2)

    left.push ({ x: p.x + nx * half, y: p.y + ny * half })
    right.push({ x: p.x - nx * half, y: p.y - ny * half })
  }

  // Cap the ends with a few extra ellipse-extent samples so the cap matches
  // the brush shape rather than abruptly squaring off. Two extra points per
  // cap keeps the geometry simple while still rounding visibly.
  const startCap = capPoints(points[0],     points[1],         a, b, ux, uy, vx, vy, -1)
  const endCap   = capPoints(points[n - 1], points[n - 2],     a, b, ux, uy, vx, vy, +1)

  return [...left, ...endCap, ...right.slice().reverse(), ...startCap]
}

// Build two interpolated points at 60° and 120° around the cap so the ellipse
// outline stays smooth at line ends.
function capPoints(p, neighbor, a, b, ux, uy, vx, vy, sign) {
  const tx = sign * (p.x - neighbor.x)
  const ty = sign * (p.y - neighbor.y)
  const tlen = Math.hypot(tx, ty) || 1
  const dx = tx / tlen, dy = ty / tlen
  // Sample the ellipse boundary in the forward (cap) hemisphere
  const out = []
  for (const angle of [Math.PI / 3, -Math.PI / 3]) {
    // rotate (dx,dy) by angle around the centre line, then take ellipse extent
    const rcos = Math.cos(angle), rsin = Math.sin(angle)
    const ex = dx * rcos - dy * rsin
    const ey = dx * rsin + dy * rcos
    const cosA = ex * ux + ey * uy
    const sinA = ex * vx + ey * vy
    const r    = Math.sqrt((a * cosA) ** 2 + (b * sinA) ** 2)
    out.push({ x: p.x + ex * r, y: p.y + ey * r })
  }
  return out
}

/** Convert an array of polygons to an SVG path-d using fill-rule="evenodd". */
export function polygonsToPathD(polygons) {
  const parts = []
  for (const poly of polygons) {
    if (poly.length < 3) continue
    parts.push(`M${Math.round(poly[0].x)} ${Math.round(poly[0].y)}`)
    for (let i = 1; i < poly.length; i++) {
      parts.push(`L${Math.round(poly[i].x)} ${Math.round(poly[i].y)}`)
    }
    parts.push('Z')
  }
  return parts.join(' ')
}
